const LANGUAGES = {
    "Acehnese (Arabic script)": "ace_Arab",
    "Acehnese (Latin script)": "ace_Latn",
    "Afrikaans": "afr_Latn",
    "Albanian": "als_Latn",
    "Amharic": "amh_Ethi",
    "Arabic": "arb_Arab",
    "Armenian": "hye_Armn",
    "Azerbaijani": "azj_Latn",
    "Bambara": "bam_Latn",
    "Bengali": "ben_Beng",
    "Bhojpuri": "bho_Deva",
    "Bulgarian": "bul_Cyrl",
    "Burmese": "mya_Mymr",
    "Catalan": "cat_Latn",
    "Chinese (Simplified)": "zho_Hans",
    "Chinese (Traditional)": "zho_Hant",
    "Croatian": "hrv_Latn",
    "Czech": "ces_Latn",
    "Danish": "dan_Latn",
    "Dutch": "nld_Latn",
    "English": "eng_Latn",
    "Estonian": "est_Latn",
    "Finnish": "fin_Latn",
    "French": "fra_Latn",
    "German": "deu_Latn",
    "Greek": "ell_Grek",
    "Gujarati": "guj_Gujr",
    "Haitian Creole": "hat_Latn",
    "Hebrew": "heb_Hebr",
    "Hindi": "hin_Deva",
    "Hungarian": "hun_Latn",
    "Icelandic": "isl_Latn",
    "Indonesian": "ind_Latn",
    "Irish": "gle_Latn",
    "Italian": "ita_Latn",
    "Japanese": "jpn_Jpan",
    "Javanese": "jav_Latn",
    "Kannada": "kan_Knda",
    "Kazakh": "kaz_Cyrl",
    "Khmer": "khm_Khmr",
    "Korean": "kor_Hang",
    "Kurdish (Latin)": "kur_Latn",
    "Lao": "lao_Laoo",
    "Latvian": "lav_Latn",
    "Lithuanian": "lit_Latn",
    "Macedonian": "mkd_Cyrl",
    "Malagasy": "mlg_Latn",
    "Malay": "zsm_Latn",
    "Malayalam": "mal_Mlym",
    "Maltese": "mlt_Latn",
    "Marathi": "mar_Deva",
    "Nepali": "nep_Deva",
    "Norwegian": "nno_Latn",
    "Pashto": "pus_Arab",
    "Persian": "fas_Arab",
    "Polish": "pol_Latn",
    "Portuguese": "por_Latn",
    "Punjabi": "pan_Guru",
    "Romanian": "ron_Latn",
    "Russian": "rus_Cyrl",
    "Serbian (Cyrillic)": "srp_Cyrl",
    "Serbian (Latin)": "srp_Latn",
    "Sinhala": "sin_Sinh",
    "Slovak": "slk_Latn",
    "Slovenian": "slv_Latn",
    "Somali": "som_Latn",
    "Spanish": "spa_Latn",
    "Sundanese": "sun_Latn",
    "Swahili": "swa_Latn",
    "Swedish": "swe_Latn",
    "Tamil": "tam_Taml",
    "Telugu": "tel_Telu",
    "Thai": "tha_Thai",
    "Turkish": "tur_Latn",
    "Ukrainian": "ukr_Cyrl",
    "Urdu": "urd_Arab",
    "Uzbek (Latin)": "uzb_Latn",
    "Vietnamese": "vie_Latn",
    "Welsh": "cym_Latn",
    "Xhosa": "xho_Latn",
    "Yoruba": "yor_Latn",
    "Zulu": "zul_Latn",
};

export default function LanguageSelector({ type, onChange, defaultLanguage }) {
    return (
        <div className='language-selector'>
            <label>{type}: </label>
            <select onChange={onChange} defaultValue={defaultLanguage}>
                {Object.entries(LANGUAGES).map(([key, value]) => (
                    <option key={key} value={value}>{key}</option>
                ))}
            </select>
        </div>
    );
}
